on:
  push:
    tags:
      - v*
jobs:
  package:
    runs-on: macos-10.15
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Chechout
        uses: actions/checkout@v2

      - name: Install Wails
        run: go get github.com/wailsapp/wails/cmd/wails@v1.16.3

      - name: Build for darwin
        run: |
          wails build -f -p

      - name: Create darwin disk image
        run: |
          brew install create-dmg
          rm build/voh
          create-dmg --volname "voh" --volicon "assets/darwin/dmg_icon.icns" --background "assets/darwin/dmg_bg.png" --window-size 512 360 --icon-size 100 --icon "voh.app" 100 185  --hide-extension "voh.app" --app-drop-link 388 185 "voh_${{ steps.version.outputs.tag }}_Darwin_x86_64.dmg" "build"

      - name: Upload darwin disk image
        uses: actions/upload-artifact@v2
        with:
          name: voh_${{ steps.version.outputs.tag }}_Darwin_x86_64.dmg
          path: voh_${{ steps.version.outputs.tag }}_Darwin_x86_64.dmg

  release:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Get version tag
        id: version
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: ${{ steps.version.outputs.tag }}
          draft: true
          prerelease: false

      - name: Download all release pacakges
        uses: actions/download-artifact@v2

      - name: Attach darwin disk image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: voh_${{ steps.version.outputs.tag }}_Darwin_x86_64.dmg/voh_${{ steps.version.outputs.tag }}_Darwin_x86_64.dmg
          asset_name: voh_${{ steps.version.outputs.tag }}_Darwin_x86_64.dmg
          asset_content_type: application/octet-stream